# Base URL of the Mastodon instance
api_base_url: 'https://mastodon.social'

# Client ID for the Mastodon application
client_id: 'GF2_wfoElucMkI9OQMnNgzl04keRMNdhbRZD4PabEHE'

# Client Secret for the Mastodon application
client_secret: ' B8Quh61pASoFDVvOCjt2elJLiZ8TxB0PHBS1FZmu9Ws'

# Access Token for the Mastodon application
access_token: 'M97v7gtS1KBYTEjvzkaidifd19ujkG_eF09soFKVX0I'

# Base URL of the Memos instance
memos_api_base_url: 'http://localhost:3001'

# Access Token for the Memos application
memos_access_token: 'eyJhbGciOiJIUzI1NiIsImtpZCI6InYxIiwidHlwIjoiSldUIn0.eyJuYW1lIjoic2l0ZWhvc3QiLCJpc3MiOiJtZW1vcyIsInN1YiI6IjEiLCJhdWQiOlsidXNlci5hY2Nlc3MtdG9rZW4iXSwiaWF0IjoxNzM2MDkwMDU0fQ.9Xp3WzC8lzhYefUYWVlaOahTOOD275Yv3e4uNMlxqvM'